### ISSUE TITLE
[SCB-1493] Adjust the structure of the generated project

### ISSUE THREAD

**Issue by kakulisen** [apache/servicecomb-toolkit#33]
When choose to generate only the provider or consumer, it is enough to generate only one project, merge the provider and model projects into one project.  I will try to adjust and submit my solution

**Comment by WillemJiang** [comment]
@kakulisen  Did you create a JIRA to check this issue?

**Comment by kakulisen** [comment]
Thanks for your check, I have created a JIRA now
