### ISSUE TITLE
检查不符合规范时退出处理

### ISSUE THREAD

**Issue by cashtang** [apache/servicecomb-toolkit#62]
检查不符合规范时没有用 System.exit(1) 来退出，makefile 这样的工具就不能很好的处理。
例如这样的Makefile。如果 verify 不通过，generate 应该也不能执行。
`
verify:
      java -jar cil.jar checkstyle -f openapi.yml

generate: verify
     java -jar cil.jar codegenerate -i openapi.yml
`

建议增加一个参数 --use-strict  表示启用严格模式，当检查不通过时用System.exit(1) 来退出。

**Comment by chanjarster** [comment]
很好的建议，我觉得只要验证失败就直接exit(1)，也不需要严格模式了，这个也符合普遍做法。
不知道你有没有兴趣提交一个PR，代码在这里：
https://github.com/apache/servicecomb-toolkit/blob/master/cli/src/main/java/org/apache/servicecomb/toolkit/cli/CheckStyleBase.java
改起来也比较简单

**Comment by chanjarster** [comment]
Close this issue 'cause it's reported in JIRA, [see this](https://issues.apache.org/jira/browse/SCB-1651)
